### PR TITLE
Add: Disclaimer added to the code.

### PR DESCRIPTION
**Pull request by ayushmanyd**
### - New File Added
disclaimer.jsx

### - File updated 
homepage.jsx
Navbar.jsx

### Screenshot -
image

### Some suggestions regarding feature & bugs -
- I can implement drag & drop file feature in which anyone can directly drag the file from file explorer, if, you want to add this feature, it will be very easy for users to use the website.
- Bug: On result showing page when we try to navigate to home it doesn't work because there is no changes in the address bar link.

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
UI is breaking with button 

and lets show it in the bottom of home page

**Comment by shivamsouravjha** [comment]
you can refer the disclaiemer page in the bottom in grow https://groww.in/ for more ideas

**Comment by shivamsouravjha** [comment]
* the first feature seems great but there we can create  a separate issue for that.
* second issue is also being worked upon.
* however there is another interesting thing I wanted to share https://github.com/shivamsouravjha/stock-frontend/issues/43

**Comment by ayushmanyd** [comment]
- Should I create it in a footer like in groww website or directly to homepage?
- If footer then should I also add the copyright thing or not?
- Should I also remove the separate Disclaimer page?

**Comment by shivamsouravjha** [comment]
* lets make the diclaimer in footer  and show it in bottom of homepage and all the pages (there will be legal issues if not, so to avoid it).
* copyright can be put as In short, most websites do not have a formal certificate; they rely on automatic copyright protection and the visible notice as a deterrent against infringement.
* yes discalimer pages should be removed it should be in all pages at the botom.

**Comment by ayushmanyd** [comment]
How about this

image

- Lets me know if some changes are to be made in this & this will be displayed on all pages.

**Comment by shivamsouravjha** [comment]
Please hide the address the number section rest everything looks fine also have update the icon.png

**Comment by shivamsouravjha** [comment]
please remove the package.json and the unneccessary yarn.lock changes

**Comment by shivamsouravjha** [comment]
image
can we try to fill this empty space? as this disclaimer should be visible hardly anyone would scroll

**Comment by ayushmanyd** [comment]
Is this ok?

image

**Comment by shivamsouravjha** [comment]
yes its perfevt @ayushmanyd

**Pull request merged**
