### PR TITLE
Add: preview of xlsx sheet on website

### PR DESCRIPTION
**Pull request by RishabhSri17**
This pull request addresses issue https://github.com/shivamsouravjha/stock-frontend/issues/6 , implementing a preview feature for XLSX files before upload.

Changes Made:
- Added generatePreview function to create a preview of selected XLSX files and implement a new component to display the XLSX preview in a table format.
- Added node-xlsx module to use it to read from or write to Excel files .

Screenshots:
Screenshot 2024-10-10 034053
Screenshot 2024-10-10 034111
Screenshot 2024-10-10 034140
Screenshot 2024-10-10 034154

Please review the changes and let me know if further adjustments are needed. Thank you!

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
its in best interst if package-lock.json is removed as it adds unnecessary amount of lines

**Comment by shivamsouravjha** [comment]
similarly yarn.lock has a lot of files which are unecessary.

**Comment by RishabhSri17** [comment]
Okay, I will do that and get back to you.

**Comment by shivamsouravjha** [comment]
@RishabhSri17 design looks great (kudos!)

let's do a thinkg instead of previewing by default let's put too button(one for upload) and one for preview. once clicked on the preview only we show the file.(not everyone want to see the file).

image

Also since we have the sample file already in https://github.com/shivamsouravjha/stock-frontend/tree/master/public (sample.xlsx) let's put an update instead of showing ~
`
`To download supported format.
`
let's use to view the supported format and lets render the sample file there only.

**Comment by RishabhSri17** [comment]
Please add Hactoberfest , Hactoberfest-accepted , accepted label .

Please review the changes and let me know if further adjustments are needed. Thank you!

**Comment by shivamsouravjha** [comment]
image


also please put the this upload button 
image

in this row 
image


because very less changes of users scrolling to bottom

**Comment by RishabhSri17** [comment]
Okay I will do this !

**Comment by RishabhSri17** [comment]
I think you haven't added the 'hacktoberfest2024' label to the repository, which is why it's reflecting like this in my PR tracking. Please add it, as it will be beneficial for me.

Screenshot -
Screenshot 2024-10-10 202951

**Comment by shivamsouravjha** [comment]
can you recheck ? I've added everywhere

**Comment by shivamsouravjha** [comment]
@RishabhSri17 please let me know if it works!

**Pull request merged**
