### PR TITLE
feat: Stocks page added

### PR DESCRIPTION
**Pull request by ayushmanyd**
feat: page to list down all the stocks added #65

#### Stocks page added:
- Checkboxes added to show different categories of the stock detail.
- Mobile friendly UI also implemented.

#### Screenshot:
image

image

### CODE REVIEW

**Comment by chintanpuggalok** [comment]
Hey @ayushmanyd looks great but the UI breaks on the mobile view. Also the stocks can be renamed to stock ranking

**Comment by ayushmanyd** [comment]
Can you share the screenshot @chintanpuggalok where the UI breaks? Also the table is scrollable (horizontally) in small devices.
Should I rename the Stocks button in Navbar or heading of the Stocks page or both?

**Comment by shivamsouravjha** [comment]
image

**Comment by ayushmanyd** [comment]
#### UI fixed

- Navbar UI updated.
- Small screen UI breaks fixed.
image
image

####
- Homepage UI also updated.
image

**Pull request merged**
