### PR TITLE
grid/table layout toggling feature

### PR DESCRIPTION
**Pull request by Abhi-m-anue**
main changes - installed and set-up shadcnui

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
seems like there is some issue with the upload button as it doesn't show and visibility is bad 
image

**Comment by shivamsouravjha** [comment]
let's make the header floating 
image


someone on 5-6 pagge should know as well the headers

**Comment by Abhi-m-anue** [comment]
Shadcn uses its own CSS variables with names primary, secondary and many more. 
I found there were few color variables  ( primary, secondary ) which were already there in the project. They became overwritten by shadcn defined variables. That's what caused the button visibility and border radius issue.
I have re-named the css variables which were previously in the project and changed everywhere it was used
old name     new name
primary        primaryColor
secondary    secondaryColor

i will change the table heading and commit the changes

**Comment by Abhi-m-anue** [comment]
Uploading sample.mp4…

**Comment by shivamsouravjha** [comment]
@Abhi-m-anue there's a merge conflict please resolve the same

**Comment by Abhi-m-anue** [comment]
Resolved please check

**Pull request merged**
