### PR TITLE
Updated the website title to StockSight and changed the logo to stag …

### PR DESCRIPTION
**Pull request by prajesh9921**
# Issue 11
# Title: updating the title of the website which is Vite + React.

## Work Done:
- I have changed the title from "vite+react" to "StockSight"
- I have added the favicon using the png available In public.
- I have added a manifest.json file to the public to add icons according to different screen sizes.
-  removed the "vite. svg" code line from index.html.

#Note
- Please let me know if anything else is needed as I am a new contributor. Thank you

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
why the package-lock.json file?

**Comment by prajesh9921** [comment]
I did npm i it added that file automatically

**Comment by shivamsouravjha** [comment]
Its not needed please remove it

**Comment by prajesh9921** [comment]
Removed the file.

**Comment by shivamsouravjha** [comment]
please also remove the yarn.lock file changes if you didn't install any new thing

**Comment by prajesh9921** [comment]
I removed the yarn.lock file. Also can you please add the label "hacktoberfest" for this issue will help a lot.

**Comment by shivamsouravjha** [comment]
Hey @prajesh9921 I think theres some miscommunication I meant that remove the yarn lock changes not the entire file itself. Have added the label

**Comment by prajesh9921** [comment]
oh ok ok  Mybad I'll revert the changes

**Pull request merged**
